review speaker start: user.speak_review_start()
review speaker recent: user.speak_review_recent("")
review speaker accepted: user.speak_review_recent("accepted")
review speaker rejected: user.speak_review_recent("rejected")
review speaker unnecessary: user.speak_review_recent("unnecessary")
review speaker all: user.speak_review_recent("all")
