from talon import Module, Context, actions, clip, settings, app

mod = Module()
ctx = Context()

@mod.action_class
class Actions:
    def write_the_clipboard():
        """Writes the clipboard to the active window"""

    def paste_transient(text: str):
        """Pastes text via clipboard without polluting clipboard history"""
        with clip.revert():
            mime = clip.MimeData()
            mime.text = text
            mime["ExcludeClipboardContentFromMonitorProcessing"] = b"true"
            mime["org.nspasteboard.AutoGeneratedType"] = b"true"
            mime["org.nspasteboard.TransientType"] = b"true"
            clip.set_mime(mime)
            actions.edit.paste()
            actions.sleep("150ms")

@ctx.action_class("user")
class Actions:
    def write_the_clipboard():
        """Writes the clipboard to the active window"""
        text = clip.text()
        actions.insert(text)