^broadcast list$:                           user.obs_show_scenes()
^broadcast <user.obs_scene_names>$:         user.obs_switch_scene(obs_scene_names)
^broadcast <user.letter>$:                  user.obs_switch_scene_by_letter(letter)
^broadcast close$:                          user.obs_hide_scenes()
^broadcast go live$:                        user.obs_start_stream()
^broadcast start stream$:                   user.obs_start_stream()
^broadcast end stream$:                     user.obs_stop_stream()
^broadcast stop stream$:                    user.obs_stop_stream()
^broadcast start recording$:               user.obs_start_recording()
^broadcast stop recording$:                user.obs_stop_recording()
^broadcast mute$:                           user.obs_mute_mics()
^broadcast unmute$:                         user.obs_unmute_mics()
^broadcast title$:                          user.twitch_show_title()
^broadcast set title <phrase>$:             user.twitch_set_title(phrase)
